language: emacs-lisp

env:
  - CASK="${HOME}/.cask/bin/cask"

install:
  # Install Emacs
  - if [ "$EMACS" = "emacs24" ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs24 emacs24-el;
    fi
  - if [ "$EMACS" = "emacs-snapshot" ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs-snapshot &&
        sudo apt-get install -qq emacs-snapshot-el emacs-snapshot-gtk;
    fi
  # Install Cask
  - curl -fsSkL https://raw.github.com/rejeep/cask.el/master/go | sh

script:
  - make -k info check
